apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-web
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage-web
  template:
    metadata:
      labels:
        app: homepage-web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: homepage-web-nginx-conf